[package]
name = "mirage"
version = "0.1.0"
authors = ["Nathan Stocks <nathan.stocks@gmail.com>", "Josias Aurel <ndjosiasaurel@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.24.3"
num-complex = "0.2.1"
